# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-08 12:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baza_test', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Publisher',
            new_name='counters',
        ),
    ]
